### PR TITLE
add a note about minimal workers and wkhtmltopdf

### PR DESCRIPTION
**Pull request by zeroheure**
May need to be rewrited. Problem is that you can't use wkhtmltopdf with workers = 1, need at least 2 workers.

### CODE REVIEW

**Comment by yelizariev** [comment]
Do you know any link to confirm it?

**Comment by zeroheure** [comment]
Have a look in these files (from 12 and 13) :
https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_actions_report.py
https://github.com/odoo/odoo/blob/12.0/addons/web/static/src/js/chrome/action_manager_report.js

Look for the string "you need to start Odoo with at least two workers to print a pdf"

**Comment by yelizariev** [comment]
Could you also comment about CPU num. Does't really matter how much CPUs the server has?

**Comment by yelizariev** [comment]
I propose to delete reference to CPU: https://github.com/it-projects-llc/odoo-development/pull/219
Let me know what do you think about it

**Pull request merged**
