### PR TITLE
Add visual stodio code IDE

### PR DESCRIPTION
**Pull request by msh2050**
hope this will save time for others

### CODE REVIEW

**Comment by yelizariev** [comment]
@msh2050 thank you.

I wll merge it, if you fix formatting and file name

    docs/ide/Visual Stodio Code/configuration.rst
    docs/ide/visual-studio-code/configuration.rst

Otherwise, we can do it ourselves.

**Comment by yelizariev** [comment]
@msh2050 do you engage in odoo development?

**Comment by msh2050** [comment]
Dear @yelizariev thanks for replay, 
I'm pharmacist with inspire in odoo medical development. "just started"
please I will appreciate any addition/correction to the use of Visual studio code with odoo, I feel it is easier IDE for me as startup.

with best regards

**Comment by yelizariev** [comment]
Thank you.

I still cannot merge it, because it doesn't pass travis test. Could you fix it:


     /home/travis/build/it-projects-llc/odoo-development/docs/ide/visual-studio-code/configuration.rst:10: ERROR: Unexpected indentation.


You also need to create index.rst file and it to upper index.rst: https://github.com/it-projects-llc/odoo-development/blame/master/docs/ide/index.rst

Check this for documentation: https://github.com/it-projects-llc/odoo-development#contribution

**Comment by msh2050** [comment]
@yelizariev thanks for support
I learn the "reStructuredText" to correct the  indentation :+1: 

I think it is great now.

**Comment by yelizariev** [comment]
Do you have a twitter account, so I can publish the doc link and reference to you?

**Comment by msh2050** [comment]
https://twitter.com/mustafaaltai
@yelizariev this is my twitter account.

**Pull request merged**
